name: Photonics RAG CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t photonicsrag-api:ci .

      - name: Build Streamlit UI Docker image
        run: |
          docker build \
            -f Dockerfile.ui \
            -t photonicsrag-ui:ci .
